spring:
  data:
    mongodb:
      uri: mongodb://root:root@192.168.194.100:27017/admin


server:
  port: 8888

logging:
  level:
    root: info
    com:
      magic:
        tower:
          game: debug
